on: [push]
jobs:
  build:
    name: 'Hello World'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'npm i'
        run: 'npm i'
      - name: 'npm i'
        run: 'node index.js'